language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - LARAVEL=5.6.*
  - LARAVEL=5.7.*
  - LARAVEL=5.8.*
  - LARAVEL=6.0.*
  - LARAVEL=6.1.*
  - LARAVEL=6.2.*
  - LARAVEL=6.3.*
  - LARAVEL=6.4.*
  - LARAVEL=6.5.*
  - LARAVEL=6.6.*

jobs:
  fast_finish: true
  include:
    - php: 7.1
      env: LARAVEL='5.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*'
    - php: 7.1
      env: LARAVEL='5.8.*'

before_install:
  - travis_retry composer self-update
  - travis_retry composer require --no-update --no-interaction "illuminate/support:${LARAVEL}"

install:
  - travis_retry composer update --no-interaction --no-suggest --prefer-dist $COMPOSER_ARGS

script:
  - php vendor/bin/phpcs --standard=phpcs.xml.dist
  - php vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

# after_success:
#   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" && $LARAVEL == '6.6.*' ]]; then
#       travis_retry composer require php-coveralls/php-coveralls;
#       travis_retry php vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -v;
#     fi
